
pub const TPM_NO_SESSIONS_HEADER: u16 = 0x8001;
pub const TPM_SESSIONS_HEADER: u16 = 0x8002;

pub const TPM_CC_GETRANDOMNUMBER: u32 = 0x0000017B;

pub const TPM_RC_VER1: u16 = 0x100;
pub const TPM_RC_FMT1: u16 = 0x080;

#[derive(PartialEq, Eq, Debug)]
pub enum ReturnCode {
    Success,
    BadTag,
    Initialize,
    Failure,
    Sequence,
    Private,
    HMAC,
    Disabled,
    Exclusive,
    AuthType,
    AuthMissing,
    Policy,
    PCR,
    PCRChanged,
    Upgrade,
    TooManyContexts,
    AuthUnavaliable,
    Reboot,
    Unbalanced,
    CommandSize,
    CommandCode,
    AuthSize,
    AuthContext,
    NVRange,
    NVSize,
    NVLocked,
    NVAuthorization,
    NVUninitialized,
    NVSpace,
    NVDefined,
    BadContext,
    CPHash,
    Parent,
    NeedsTest,
    NoResult,
    Sensitive,
    ReadOnly,
    Asymmetric,
    Attributes,
    Hash,
    Value,
    Hierarchy,
    KeySize,
    MGF,
    Mode,
    Type,
    Handle,
    KDF,
    Range,
    AuthFail,
    Nonce,
    PP,
    Scheme,
    Size,
    Symmetric,
    Tag,
    Selector,
    Insufficient,
    Signature,
    Key,
    PolicyFail,
    Integrity,
    Ticket,
    ReservedBits,
    BadAuth,
    Expired,
    PolicyCC,
    Binding,
    Curve,
    EccPoint,
    FWLimited,
    SVNLimited,
    Channel,
    ChannelKey,
    RCNotRecognized //out of spec, created for code coherence purposes
}
